services:
  model:
    container_name: cryptobot-model
    image: cryptobot/model:latest
    build:
      context: ${PWD}
      dockerfile: ./model/Dockerfile
    volumes:
      - model_fit:/src/model_fit
    environment:
      KLINESDB_HOST: klines-db
      KLINESDB_USER: root
      KLINESDB_PASSWORD: root
      KLINESDB_DBNAME: klines

volumes:
  model_fit:
    name: model_fit

networks:
  default:
    external:
      name: data-network