services:
  model-serve:
    container_name: model-serve
    image: tensorflow/serving:2.13.0
    depends_on:
      model-fit:
        condition: service_completed_successfully
    command:
      - --model_config_file=/models/models.config
      - --model_config_file_poll_wait_seconds=60
    ports:
      - 8501:8501
    volumes:
      - model_fit:/models/

  model-fit:
    container_name: model-fit
    image: cryptobot/model:latest
    build:
      context: ${PWD}
      dockerfile: ./model/Dockerfile.model-fit
    volumes:
      - model_fit:/src/model_fit
    environment:
      KLINESDB_HOST: klines-db
      KLINESDB_USER: root
      KLINESDB_PASSWORD: root
      KLINESDB_DBNAME: klines

volumes:
  model_fit:
    name: model_fit

networks:
  default:
    name: data-network
    external: true