apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: pod-creator
rules:
- apiGroups:
  - ""
  resources:
  - pods
  verbs:
  - create
  - get
  - list
  - watch
  - delete
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: airflow-executor:create-pod
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: pod-creator
subjects:
- kind: ServiceAccount
  name: default
  namespace: airflow
---
# TODO: secret (cf. secrets.CRYPTOBOT_SECRET)
apiVersion: v1
kind: ConfigMap
metadata:
  name: airflow-config
  namespace: airflow
data:
  AIRFLOW__CORE__EXECUTOR: KubernetesExecutor
  AIRFLOW__CORE__SQL_ALCHEMY_CONN: mysql+mysqldb://root:password@db.default.svc.cluster.local:3306/klines_history
  AIRFLOW__KUBERNETES__NAMESPACE: airflow
  AIRFLOW__KUBERNETES__WORKER_SERVICE_ACCOUNT_NAME: default
  AIRFLOW__KUBERNETES__IN_CLUSTER: 'true'
  AIRFLOW__KUBERNETES_EXECUTOR__POD_TEMPLATE_FILE: /opt/airflow/executor-pod-template.yml
  MYSQL_HOST_PREDICTIONS: db.default.svc.cluster.local
  MYSQL_USER_PREDICTIONS: root
  MYSQL_PASSWORD_PREDICTIONS: password
  MYSQL_DATABASE_PREDICTIONS: klines_history
  PREDICT_SERVER_HOST: c-predict.default.svc.cluster.local:8501
  WEB_API_HOST: api-container.default.svc.cluster.local:8000
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: exectutor-config
  namespace: airflow
data:
  executor-pod-template.yml: |
    apiVersion: v1
    kind: Pod
    metadata:
      name: airflow-executor-template
    spec:
      containers:
        - name: base
          image: apache/airflow:2.7.1
          envFrom:
            - configMapRef:
                name: airflow-config
          imagePullPolicy: IfNotPresent
          volumeMounts:
            - mountPath: /opt/airflow/logs
              name: airflow-logs
            - mountPath: /opt/airflow/dags
              name: airflow-dags
      restartPolicy: Never
      volumes:
        - name: airflow-logs
          hostPath:
            path: /home/cryptobot/airflow/logs
        - name: airflow-dags
          hostPath:
            path: /home/cryptobot/airflow/dags
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: airflow
  namespace: airflow
spec:
  replicas: 1
  selector:
    matchLabels:
      name: airflow
  template:
    metadata:
      labels:
        name: airflow
    spec:
      # automountServiceAccountToken: true
      initContainers:
      - image: apache/airflow:2.7.1
        name: airflow-migrate-db
        args:
          - db
          - migrate
        envFrom:
          - configMapRef:
              name: airflow-config
      - image: apache/airflow:2.7.1
        name: airflow-create-user
        args: ["users", "create", "--username", "cryptobot", "--password", "cryptic", "--firstname", "Peter", "--lastname", "Parker", "--role", "Admin", "--email", "spiderman@superhero.org"]
        envFrom:
          - configMapRef:
              name: airflow-config
      containers:
      - name: airflow-webserver
        image: apache/airflow:2.7.1
        args:
          - webserver
          - -p
          - "8080"
        envFrom:
          - configMapRef:
              name: airflow-config
        imagePullPolicy: Always
        volumeMounts:
          - mountPath: /opt/airflow/logs/
            name: airflow-logs
          - mountPath: /opt/airflow/dags/
            name: airflow-dags
      - name: airflow-scheduler
        image: apache/airflow:2.7.1
        args:
          - scheduler
        envFrom:
          - configMapRef:
              name: airflow-config
        # TODO: sevice + ingress
        ports:
          - containerPort: 8080
            hostPort: 8080
        imagePullPolicy: Always
        volumeMounts:
          - mountPath: /opt/airflow/logs/
            name: airflow-logs
          - mountPath: /opt/airflow/dags/
            name: airflow-dags
          - name: exectutor-config-volume
            mountPath: /opt/airflow/executor-pod-template.yml
            subPath: executor-pod-template.yml
      volumes:
        - name: airflow-logs
          hostPath:
            path: /home/cryptobot/airflow/logs
        - name: airflow-dags
          hostPath:
            path: /home/cryptobot/airflow/dags
        - name: exectutor-config-volume
          configMap:
            name: exectutor-config
