apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.30.0 (HEAD)
  creationTimestamp: null
  labels:
    io.kompose.service: api-container
  name: api-container
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: api-container
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
        kompose.version: 1.30.0 (HEAD)
      creationTimestamp: null
      labels:
        io.kompose.network/requester-network: "true"
        io.kompose.service: api-container
    spec:
      containers:
        - image: cryptobot/web-api:latest
          name: web-api
          ports:
            - containerPort: 8000
              hostPort: 8000
              protocol: TCP
          resources: {}
      restartPolicy: Always
status: {}
