apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.30.0 (HEAD)
  creationTimestamp: null
  labels:
    io.kompose.service: app
  name: app
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: app
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
        kompose.version: 1.30.0 (HEAD)
      creationTimestamp: null
      labels:
        io.kompose.network/requester-network: "true"
        io.kompose.service: app
    spec:
      containers:
        - env:
            - name: MYSQL_DATABASE_KLINES
              value: klines_history
            - name: MYSQL_DATABASE_PREDICTIONS
              value: klines_history
            - name: MYSQL_HOST_KLINES
              value: db
            - name: MYSQL_HOST_PREDICTIONS
              value: db
            - name: MYSQL_PASSWORD_KLINES
              value: password
            - name: MYSQL_PASSWORD_PREDICTIONS
              value: password
            - name: MYSQL_USER_KLINES
              value: root
            - name: MYSQL_USER_PREDICTIONS
              value: root
            - name: PREDICT_SERVER_HOST
              value: c-predict:8501
          image: requester/app:latest
          name: c-script
          resources: {}
          volumeMounts:
            - mountPath: /app/data
              name: preprocessing-data
      restartPolicy: Never
      volumes:
        - name: preprocessing-data
          persistentVolumeClaim:
            claimName: preprocessing-data
status: {}
