apiVersion: v1
kind: Secret
metadata:
  name: mysql-user-pass
type: Opaque
data:
  PASSWORD: ZGF0YXNjaWVudGVzdDEyMzQ=
---
apiVersion: v1
kind: Secret
metadata:
  name: mysql-db-name
type: Opaque
data:
  DATABASE_NAME: TWFpbg==