apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.30.0 (HEAD)
  creationTimestamp: null
  labels:
    io.kompose.service: data
  name: data
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: data
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
        kompose.version: 1.30.0 (HEAD)
      creationTimestamp: null
      labels:
        io.kompose.network/requester-network: "true"
        io.kompose.service: data
    spec:
      containers:
        - env:
            - name: KLINESDB_DBNAME
              value: klines_history
            - name: KLINESDB_HOST
              value: db
            - name: KLINESDB_PASSWORD
              value: password
            - name: KLINESDB_USER
              value: root
          image: cryptobot/data:latest
          name: historical-data
          resources: {}
      restartPolicy: Always
status: {}
