apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.30.0 (HEAD)
  creationTimestamp: null
  labels:
    io.kompose.service: db-predict
  name: db-predict
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: db-predict
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
        kompose.version: 1.30.0 (HEAD)
      creationTimestamp: null
      labels:
        io.kompose.network/requester-network: "true"
        io.kompose.service: db-predict
    spec:
      containers:
        - env:
            - name: MYSQL_DATABASE
              value: predictions_history
            - name: MYSQL_ROOT_PASSWORD
              value: password
          image: mysql:latest
          livenessProbe:
            exec:
              command:
                - mysqladmin
                - ping
                - -h
                - localhost
            failureThreshold: 5
            periodSeconds: 10
            timeoutSeconds: 5
          name: db-predict
          ports:
            - containerPort: 3306
              hostPort: 3307
              protocol: TCP
          resources: {}
          securityContext:
            capabilities:
              add:
                - SYS_NICE
          volumeMounts:
            - mountPath: /var/lib/mysql
              name: predictions-data
      restartPolicy: Always
      volumes:
        - name: predictions-data
          persistentVolumeClaim:
            claimName: predictions-data
status: {}
