version: '3.8'

networks:
  requester_network:
    external: true

services:
  app:
    build:
      context: .
    environment:
      MYSQL_HOST_KLINES: db
      MYSQL_USER_KLINES: root
      MYSQL_DATABASE_KLINES: klines_history
      MYSQL_PASSWORD_KLINES: password
      MYSQL_HOST_PREDICTIONS: db_predict
      MYSQL_USER_PREDICTIONS: root
      MYSQL_DATABASE_PREDICTIONS: predictions_history
      MYSQL_PASSWORD_PREDICTIONS: password
      PREDICT_SERVER_HOST: c-predict:8501
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - preprocessing_data:/app/data
    networks:
      - requester_network
    
  db:
    image: mysql:latest
    cap_add:
      - SYS_NICE
    restart: always
    environment:
      MYSQL_DATABASE: klines_history
      MYSQL_ROOT_PASSWORD: password
    ports:
      - '3306:3306'
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5
    volumes:
      - klines_data:/var/lib/mysql
    networks:
      - requester_network

  db_predict:
    image: mysql:latest
    cap_add:
      - SYS_NICE
    restart: always
    environment:
      MYSQL_DATABASE: predictions_history
      MYSQL_ROOT_PASSWORD: password
    ports:
      - '3307:3306'
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5
    volumes:
      - predictions_data:/var/lib/mysql
    networks:
      - requester_network

volumes:
  klines_data: 
    name: klines_data
  preprocessing_data:
    name: preprocessing_data
  predictions_data: 
    name: predictions_data

