apiVersion: v1
kind: Secret
metadata:
  name: api-secrets
type: Opaque
data:
  MYSQL_DATABASE_PREDICTIONS: ${{ secrets.MYSQL_DATABASE_PREDICTIONS }}
  MYSQL_HOST_PREDICTIONS: ${{ secrets.MYSQL_HOST_PREDICTIONS }}
  MYSQL_PASSWORD_PREDICTIONS: ${{ secrets.MYSQL_PASSWORD_PREDICTIONS }}
  MYSQL_USER_PREDICTIONS: ${{ secrets.MYSQL_USER_PREDICTIONS }}
---
apiVersion: v1
kind: Secret
metadata:
  name: db-secrets
type: Opaque
data:
  MYSQL_DATABASE: ${{ secrets.MYSQL_DATABASE }}
  MYSQL_ROOT_PASSWORD: ${{ secrets.MYSQL_ROOT_PASSWORD }}