# apiVersion: networking.k8s.io/v1
# kind: Ingress
# metadata:
#   name: api-ingress
# spec:
#   defaultBackend:
#     service:
#       name: api-container
#       port:
#         number: 8000

apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: api-ingress
  namespace: default
spec:
  rules:
    - host: localhost
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: api-container
                port:
                  number: 8000