apiVersion: v1
kind: Secret
metadata:
  name: api-secrets
type: Opaque
data:
  MYSQL_DATABASE_PREDICTIONS: a2xpbmVzX2hpc3Rvcnk=
  MYSQL_HOST_PREDICTIONS: ZGI=
  MYSQL_PASSWORD_PREDICTIONS: cGFzc3dvcmQ=
  MYSQL_USER_PREDICTIONS: cm9vdA==
---
apiVersion: v1
kind: Secret
metadata:
  name: db-secrets
type: Opaque
data:
  MYSQL_DATABASE: a2xpbmVzX2hpc3Rvcnk=
  MYSQL_ROOT_PASSWORD: cGFzc3dvcmQ=