name: Control Push
on: push
jobs:
  setup-env:
    runs-on: ubuntu-latest
    steps:
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: "3.11.4"

    - name: Install Dependancies
      run: pip install -r requirements.txt

    - name: Run tests
      run: |
        pytest
