name: Kubernetes Deployment on Branch Push

on:
  push:
    branches:
      - kub  

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Kubernetes CLI
      uses: azure/setup-kubectl@v3
      with:
        kubeconfig: ${{ secrets.KUBE_CONFIG_DATA }}
      env:
        KUBECONFIG: ${{ secrets.KUBE_CONFIG_DATA }}
    
    - name: Debug KUBECONFIG
      run: |
        echo "KUBECONFIG environment variable:"
        echo $KUBECONFIG
        echo "Contents of KUBE_CONFIG_DATA:"
        echo "${{ secrets.KUBE_CONFIG_DATA }}"

    - name: Deploy to Kubernetes
      run: |
        kubectl apply -f kubernetes/cryptobot-deployment.yaml
        kubectl apply -f kubernetes/cryptobot-service.yaml
        kubectl apply -f kubernetes/cryptobot-secret.yaml
        kubectl apply -f kubernetes/cryptobot-pvc.yaml
        kubectl apply -f kubernetes/cryptobot-ingress.yaml
        kubectl apply -f kubernetes/cryptobot-cronjob-weeklyTask.yaml
        kubectl apply -f kubernetes/cryptobot-cronjob-minutelyTask.yaml
        kubectl apply -f kubernetes/cryptobot-cronjob-hourlyTask.yaml
        kubectl apply -f kubernetes/cryptobot-cronjob-dailyTask.yaml