name: Kubernetes Deployment on Branch Push

on:
  push:
    branches:
      - kub  

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Kubernetes CLI
      uses: azure/setup-kubectl@v1
      with:
        kubeconfig: ${{ secrets.KUBE_CONFIG_DATA }}

    - name: Deploy to Kubernetes
        run: |
          kubectl apply -f kubernetes/cryptobot-deployment.yaml \
            kubernetes/cryptobot-service.yaml \
            kubernetes/cryptobot-secret.yaml \
            kubernetes/cryptobot-pvc.yaml \
            kubernetes/cryptobot-ingress.yaml \
            kubernetes/cryptobot-cronjob-weeklyTask.yaml \
            kubernetes/cryptobot-cronjob-minutelyTask.yaml \
            kubernetes/cryptobot-cronjob-hourlyTask.yaml \
            kubernetes/cryptobot-cronjob-dailyTask.yaml