apiVersion: v1
kind: Config
clusters:
- cluster:
    certificate-authority: /Users/johannambrugeat/.minikube/ca.crt
    server: https://192.168.64.2:8443
  name: minikube
contexts:
- context:
    cluster: minikube
    user: minikube
  name: minikube
current-context: minikube
users:
- name: minikube
  user:
    client-certificate: /Users/johannambrugeat/.minikube/profiles/minikube/client.crt
    client-key: /Users/johannambrugeat/.minikube/profiles/minikube/client.key