name: Kubernetes Deployment

on:
  push:
    branches:
      - kub
      - dev

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Use Node.js 16
      uses: actions/setup-node@v2
      with:
        node-version: 16

    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Kubernetes CLI
      uses: azure/setup-kubectl@v1
      with:
        kubeconfig: ${{ secrets.KUBE_CONFIG_DATA }}  # Configurez les secrets pour votre configuration kubectl

    - name: Deploy to Kubernetes
      run: |
        kubectl apply -f kubernetes/cryptobot-deployment.yaml